### ISSUE TITLE
Privacy breach ?

### ISSUE THREAD

**Issue by suoko** [ministero-salute/it-dgc-verificaC19-android#167] opened 2021-10-15 16:25 UTC
It looks like that with the QR you can obtain the date a person was shot a vaccine or has done a covid-test, together with all the history.
This way an employer could know if a person was vaccinated or not.

**Comment by popolla** [comment] 2021-10-18 11:20
This is not a bug since it has nothing to do with the specific application, and everything to do with the international specifications for the contents of the QR code. There's never been privacy upon that data from the very beginning. Italy seemingly tried to mitigate the issue by providing an application that does not show that type of information directly in the GUI, then saying that application is the only allowed one. But by definition the information inside the QR code isn't secret, anyone can decode it. This app is even too good when it comes to this argument. I understand your frustration, but please consider closing this issue, developers really can do nothing about it.

**Comment by suoko** [comment] 2021-10-18 12:14
Who should be informed about that ? Since this is the "ministero della salute" official account, I hope the message will get to those managing the APIs. I think it being just a question of narrowing the data query down a bit

**Closed as completed** 2021-10-18 12:14 UTC
Labels: bug

**Comment by popolla** [comment] 2021-10-18 20:05
Everybody is informed about that.
Nope, unfortunately it's not just a question of narrowing the data query down. The APIs don't decide the fields encoded in the QR. That's practically the same across all Europe. The question is, the national rules for DGC validation are based on both the type and the time of the "event" (vaccination shot, test, etc) and validation must be performed device-side, mostly to avoid any kind of tracking of the holder. Therefore, type and time of the "event" must be stored inside the DGC, there's no escape from that.

**Comment by jumpjack** [comment] 2021-11-02 14:02
The data contained in the QRcode are exactly the same available in human readable format of the Digital Covid Certificate:

Paper specification: https://ec.europa.eu/health/sites/default/files/ehealth/docs/covid-certificate_paper_guidelines_en.pdf

JSON specification: https://ec.europa.eu/health/sites/default/files/ehealth/docs/digital-green-certificates_v2_en.pdf

No encryption is applied, only digital signing.


Whoever finds you qrcode around could read same information that he could read if he found your printed greenpass.
